# -*- coding: utf-8 -*-
"""finetuning_and_predicition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123NSxZ8F2FWeUjYdOEiGV9tEN4ElVyFa
"""

#Clone the BERT github repository
!git clone https://github.com/google-research/bert.git

cd bert

#BERT has release BERT-Base and BERT-Large models. 
#We have chosen BERT-Large-Uncased Model (24-layer, 1024-hidden, 16-heads, 340M parameters). 
#Uncased means that the text has been lowercased before WordPiece tokenization, e.g., John Smith becomes john smith.
!wget https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-24_H-1024_A-16.zip

# Unzip the pretrained model
!unzip uncased_L-24_H-1024_A-16.zip

#Download the SQUAD train and dev dataset
!wget https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v2.0.json
!wget https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v2.0.json

import datetime
import json
import os
import pprint
import random
import string
import sys
import tensorflow as tf

#Verification of connection to a TPU device
assert 'COLAB_TPU_ADDR' in os.environ, 'ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!'
TPU_ADDRESS = 'grpc://' + os.environ['COLAB_TPU_ADDR']
print('TPU address is => ', TPU_ADDRESS)
#Google Colab Authentication
from google.colab import auth
auth.authenticate_user()

with tf.Session(TPU_ADDRESS) as session:
  print('TPU devices:')
  pprint.pprint(session.list_devices())

  # Upload credentials to TPU.
  with open('/content/adc.json', 'r') as f:
    auth_info = json.load(f)
  tf.contrib.cloud.configure_gcs(session, credentials=auth_info)

#Making a connection to project by project-ID
!gcloud config set project orbital-linker-275922

!gsutil ls

#Creation of a output directory at Google Cloud Storage
BUCKET = 'example_wedt' #@param {type:"string"}
assert BUCKET, '*** Must specify an existing GCS bucket name ***'
output_dir_name = 'bert_output' #@param {type:"string"}
BUCKET_NAME = 'gs://{}'.format(BUCKET)
OUTPUT_DIR = 'gs://{}/{}'.format(BUCKET,output_dir_name)
tf.gfile.MakeDirs(OUTPUT_DIR)
print('***** Model output directory: {} *****'.format(OUTPUT_DIR))

ls -l

#Moving Pre-trained Model at Google Cloud Storage bucket
!gsutil mv /content/bert/uncased_L-24_H-1024_A-16 $BUCKET_NAME

#Running the training on TPU
!python run_squad.py \
  --vocab_file=$BUCKET_NAME/uncased_L-24_H-1024_A-16/vocab.txt \
  --bert_config_file=$BUCKET_NAME/uncased_L-24_H-1024_A-16/bert_config.json \
  --init_checkpoint=$BUCKET_NAME/uncased_L-24_H-1024_A-16/bert_model.ckpt \
  --do_train=True \
  --train_file=train-v2.0.json \
  --do_predict=True \
  --predict_file=dev-v2.0.json \
  --train_batch_size=24 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --use_tpu=True \
  --tpu_name=grpc://10.53.237.170:8470 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --version_2_with_negative=True \
  --output_dir=$OUTPUT_DIR

# Commented out IPython magic to ensure Python compatibility.
# #Creation of the first JASON testing file
# #The data in the file in the SQuAD dataset format
# %%writefile input_file.json
# {
#     "version": "v2.0",
#     "data": [
#         {
#             "title": "your_title",
#             "paragraphs": [
#                 {
#                     "qas": [
#                         {
#                             "question": "Who is current CEO?",
#                             "id": "56ddde6b9a695914005b9628",
#                             "is_impossible": ""
#                         },
#                         {
#                             "question": "Who founded google?",
#                             "id": "56ddde6b9a695914005b9629",
#                             "is_impossible": ""
#                         },
#                         {
#                             "question": "when did IPO take place?",
#                             "id": "56ddde6b9a695914005b962a",
#                             "is_impossible": ""
#                         }
#                     ],
#                     "context": "Google was founded in 1998 by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University in California. Together they own about 14 percent of its shares and control 56 percent of the stockholder voting power through supervoting stock. They incorporated Google as a privately held company on September 4, 1998. An initial public offering (IPO) took place on August 19, 2004, and Google moved to its headquarters in Mountain View, California, nicknamed the Googleplex. In August 2015, Google announced plans to reorganize its various interests as a conglomerate called Alphabet Inc. Google is Alphabet's leading subsidiary and will continue to be the umbrella company for Alphabet's Internet interests. Sundar Pichai was appointed CEO of Google, replacing Larry Page who became the CEO of Alphabet."                
#                  }
#             ]
#         }
#     ]
# }

# Commented out IPython magic to ensure Python compatibility.
# #Creation of the second JASON testing file containing questions about COVID
# %%writefile input_file2.json
# {
#     "version": "v2.0",
#     "data": [
#         {
#             "title": "your_title",
#             "paragraphs": [
#                 {
#                     "qas": [
#                         {
#                             "question": "What is COVID-19?",
#                             "id": "76ddde6b9a695914005b9628",
#                             "is_impossible": ""
#                         },
#                         {
#                             "question": "What are symptoms of COVID-19?",
#                             "id": "76ddde6b9a695914005b9629",
#                             "is_impossible": ""
#                         },
#                         {
#                             "question": "How many people recover from COVID?",
#                             "id": "76ddde6b9a695914005b962a",
#                             "is_impossible": ""
#                         },
#                         {
#                             "question": "From where corona started?",
#                             "id": "76ddde6b9a695914005b962b",
#                             "is_impossible": ""
#                         },
#                         {
#                             "question": "Who requires medical attention?",
#                             "id": "76ddde6b9a695914005b962c",
#                             "is_impossible": ""
#                         }
#                     ],
#                     "context": "COVID-19 is the infectious disease caused by the most recently discovered coronavirus. This new virus and disease were unknown before the outbreak began in Wuhan, China, in December 2019. The most common symptoms of COVID-19 are fever, tiredness, and dry cough. Some patients may have aches and pains, nasal congestion, runny nose, sore throat or diarrhea. These symptoms are usually mild and begin gradually. Some people become infected but don’t develop any symptoms and don't feel unwell. Most people (about 80%) recover from the disease without needing special treatment. Around 1 out of every 6 people who gets COVID-19 becomes seriously ill and develops difficulty breathing. Older people, and those with underlying medical problems like high blood pressure, heart problems or diabetes, are more likely to develop serious illness. People with fever, cough and difficulty breathing should seek medical attention."                
#                  }
#             ]
#         }
#     ]
# }

#Performing custom prediction on the testing file
!python run_squad.py \
  --vocab_file=$BUCKET_NAME/uncased_L-24_H-1024_A-16/vocab.txt \
  --bert_config_file=$BUCKET_NAME/uncased_L-24_H-1024_A-16/bert_config.json \
  --init_checkpoint=$OUTPUT_DIR/model.ckpt-10859 \
  --do_train=False \
  --max_query_length=30  \
  --do_predict=True \
  --predict_file=input_file.json \
  --predict_batch_size=8 \
  --n_best_size=3 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --output_dir=$OUTPUT_DIR/output/

#Perform predcition on the second testing file
!python run_squad.py \
  --vocab_file=$BUCKET_NAME/uncased_L-24_H-1024_A-16/vocab.txt \
  --bert_config_file=$BUCKET_NAME/uncased_L-24_H-1024_A-16/bert_config.json \
  --init_checkpoint=$OUTPUT_DIR/model.ckpt-10859 \
  --do_train=False \
  --max_query_length=30  \
  --do_predict=True \
  --predict_file=input_file2.json \
  --predict_batch_size=8 \
  --n_best_size=3 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --output_dir=$OUTPUT_DIR/output2/